### ISSUE TITLE
Build and flash

### ISSUE THREAD

**Issue by aovrn** [andersm/usbcart#2]
Hi!
I tried to build pcb and flash it.
I built romimage.bin with this tool: gnush_v10.03_elf-1-1.i386.rpm (it's right compiler?)
Linker outputs this warning:
 .../4.5-GNUSH_v10.03/../../../../sh-elf/bin/ld: warning: dot moved backwards before `.rodata.align2'
Is it problem or I can ignore it?

And second question how can I flash firmware to chip? Any information about it would be useful for me. I got fail with swap trick, so I need flash firmware before build cart.

Thank you very much!

**Comment by andersm** [comment]
It's probably not a problem, but can't say for sure. The toolchains I'm using don't produce any warnings.

If you can't get code running on the Saturn you'll have to use an eprommer to program the chips before soldering them.

**Comment by aovrn** [comment]
Thank you for answer!
I need to flash raw romimage.bin or it needs some preparation?

**Comment by andersm** [comment]
The compiled image is ready for flashing.

**Comment by aovsu** [comment]
Thank you
