### ISSUE TITLE
Can't Open in KiCad 5.1.2

### ISSUE THREAD

**Issue by JensRestemeier** [andersm/usbcart#3]
I just want to mention that I've got difficulties opening the schematic in KiCad, as it reports missing libraries, and some files are still the old file formats. Is it possible that you've got untracked/unsubmitted files for the KiCad project?

**Comment by andersm** [comment]
The cache library was missing from the repository, but has been added. It's is still going to complain about missing libraries, but that's a consequence of KiCad 5 changing how libraries are handled.
