### ISSUE TITLE
Project URL in Readme.md points to a dead site

### ISSUE THREAD

**Issue by nekoniaow** [andersm/usbcart#4]
Hi,

The Readme refers to an URL to obtain more details about the project but unfortunately it points to a currently dead site (https://antime.kapsi.fi/~antime/sega/usbcart/usbcart.html) which does not seem to have been archived by archive.org alas.

Searching around the web it looks like the proper link should be this one:
http://antime.kapsi.fi/sega/usbcart.html

**Comment by andersm** [comment]
The redirect should work now.
