### ISSUE TITLE
Suggestions: Silkscreen + Flash footprints

### ISSUE THREAD

**Issue by JensRestemeier** [andersm/usbcart#5]
I finally got my cart to work! Awesome project!

Some (low priority) suggestions:
- could you mark the odd and even address flash ROMs on the silkscreen?
- would it be possible to wire the extra address lines on the flash footprints for 39sf040? 
- is there enough room for through-hole PLCC sockets for the flash, in addition to the SMD footprints?

**Comment by andersm** [comment]
Modifying the silkscreen would be redundant. That information is already provided through the part number and schematic.

The cartridge design is complete, as far as I'm concerned, but feel free to fork and modify it. Though if you do, the layout and routing should be completely redone, it is quite messy.
