### ISSUE TITLE
¿Puedes compartir las herramientas de compilación?

### ISSUE THREAD

**Issue by ribenyamazun123** [andersm/usbcart#6]
¿Puedes compartir las herramientas de compilación?

**Comment by andersm** [comment]
Sorry, I don't speak Spanish.

**Comment by ribenyamazun123** [comment]
Can you share the compiler of the arflasher folder?

**Comment by andersm** [comment]
No, but you can try creating one with e.g. Crosstool-NG. There's also various binary distributions for different operating systems, e.g. SSSDK maintained by vbt, Jo Engine, etc.
